apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-sa-binding
  namespace: homework
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: homework
roleRef:
  kind: ClusterRole
  name: metrics-monitroring-role
  apiGroup: rbac.authorization.k8s.io