apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pv-claim1
  namespace: homework
spec:
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
