apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-sa-binding
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd-sa
  namespace: homework
  apiGroup: ""
roleRef:
  kind: Role
  name: sa-cd-admin
  apiGroup: rbac.authorization.k8s.io
