apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config1
  namespace: homework
data:
  nginx.conf: |
    server {
      location / {
          root /data/www;
      }

      location /images/ {
          root /data;
      }
    }
